---
# Standards: 0.2
- hosts: all
  connection: local
  vars_files:
    - defaults/main.yml

  tasks:
    - name: Set string
      set_fact:
        options: "{{ compile_boost_with }}"

    - name: Display string
      debug:
        msg: "{{ compile_boost_with }}"
...
